### PR TITLE
Test xenial

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Review by Bodigrim — APPROVED** [review]

**Comment by Lysxia** [comment]
I guess we can merge this first and fix the conflict in the other PR, which needs minor changes and benefits from the extra testing from this PR anyway.

**Comment by sjakobi** [comment]
When can we expect a release containing this fix? I hope the fix will be bundled with GHC 9.4.1?!

**Comment by Bodigrim** [comment]
The fix is irrelevant for GHC 9.4: `text` as a boot library is built on GHC build servers with an up-to-date Ubuntu, and users do not need to rebuild it.

**Comment by sjakobi** [comment]
Ah, that good to know.

Nevertheless, I expect that once GHC 9.4 accelerates the migration towards `text-2`, more users will also attempt to use it with older GHCs and on older platforms. It would be good to have a fixed release by then.

**Pull request merged**
