### PR TITLE
allow template-haskell version 2.22

### PR DESCRIPTION
**Pull request by BebeSparkelSparkel**

### CODE REVIEW

**Review by Bodigrim — APPROVED** [review]
Since it is trivial, let me merge without a second review.

**Comment by phadej** [comment]
I'm confused. GHC-9.10.1 ships with `th-2.22` and `text-2.1.1`. The https://hackage.haskell.org/package/text-2.1.1/revisions/ was applied two days ago. 

Did GHC ship with some unversioned commit of `text`?

**Comment by Bodigrim** [comment]
Shipping unversioned commit would be more or less fine, it happens all the time, but GHC was apparently shipped with a commit completely missing from upstream repo, which is quite undesirable.

**Comment by phadej** [comment]
By unversioned I meant "not in the version control system" (i.e. not *untagged*)

**Pull request merged**
