### PR TITLE
Adapt for changes to liftTyped

### PR DESCRIPTION
**Pull request by mpickering**

### CODE REVIEW

**Comment by bgamari** [comment]
@sjakobi, could you review/merge this?

**Comment by sjakobi** [comment]
@bgamari, unfortunately I am very unfamiliar with TH, so I can't really review this.

I had simply noticed this PR because in `hnix`, we have a `Lift` instance that I'm not sure how to implement `liftTyped` in.

@RyanGlScott, you've previously worked on this instance, could you help with the review?

I also don't have merge permissions for this repo.

(CC @hvr)

**Comment by mgsloan** [comment]
FWIW, LGTM :)

**Comment by RyanGlScott** [comment]
This is the standard way of implementing `liftTyped` for a data type with an unorthodox `lift` implementation. As such, this should be uncontroversial.

**Pull request merged**
