### PR TITLE
Bump ghc-prim upper bound

### PR DESCRIPTION
**Pull request by bgamari**
GHC 8.10 uses ghc-prim-0.6.1 currently.

### CODE REVIEW

**Comment by RyanGlScott** [comment]
This is required to unblock https://gitlab.haskell.org/ghc/ghc/issues/17956.

**Comment by hvr** [comment]
@RyanGlScott where did the mysterious `ghc-prim-0.6.0` release go?

**Comment by RyanGlScott** [comment]
I'm afraid I have no idea, since I'm not the Hackage maintainer of `ghc-prim`.

**Comment by nikita-volkov** [comment]
Can we get this released on Hackage please?

**Pull request merged**
