### PR TITLE
Add Data.Text.show and Data.Text.Lazy.show

### LINKED ISSUE #183: Add tshow function
In multiple different projects that I have worked on I've encountered variations on the following function:

```haskell
tshow :: Show a => a -> Text
tshow = T.pack . show
```

It would be great if the text package could add this to eliminate the redundancy and confusion.

### PR DESCRIPTION
**Pull request by Lysxia**
Closes #183

### CODE REVIEW

**Review by Bodigrim — APPROVED** [review]

**Comment by Bodigrim** [comment]
Awesome!

**Comment by andreasabel** [comment]
Maybe this should have been in 2.2 rather 2.1.2. 
Formally it is ok to add a new function in a minor bump.
However, since `show` is in Prelude, everyone importing `Data.Text` unqualified will get breakage.
So maybe 2.2 would have been wiser...
- https://codeberg.org/valpackett/http-link-header/issues/1

**Comment by Bodigrim** [comment]
It's abundantly obvious that importing `Data.Text` unqualified is unwise, because there dozens of clashes with `Prelude`, be it with `show` or without it.

Even in a hindsight, making it 2.2 would not save us any work: since `http-link-header` has no upper bounds at all, you'd still have to revise it... plus hundreds of innocent packages with `text < 2.2` atop of it.

**Comment by andreasabel** [comment]
Yeah, I guess that's right.

**Pull request merged**
